import React, { useState, useEffect, useRef } from 'react'
import * as QRCode from 'qrcode'

interface SignData {
  projectName: string
  projectNumber: string
  siteAddress: string
  engineer: string
  contractor: string
  startDate: string
  emergencyContact: string
  url: string
}

const DEFAULTS: SignData = {
  projectName:      'Thorndon Retaining Wall Upgrade',
  projectNumber:    'TPT-2026-001',
  siteAddress:      '45 Tinakori Road, Thorndon, Wellington 6011',
  engineer:         'J. Smith CPEng',
  contractor:       'Wellington Civil Contractors Ltd',
  startDate:        '2026-07-01',
  emergencyContact: '0800 111 222',
  url:              'https://tpt-infrastructure.nz/project/TPT-2026-001',
}

const QRSiteSign: React.FC = () => {
  const [sign, setSign]       = useState<SignData>(DEFAULTS)
  const [qrUrl, setQrUrl]     = useState<string>('')
  const signRef               = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const text = sign.url || [sign.projectNumber, sign.projectName, sign.siteAddress].join(' | ')
    QRCode.toDataURL(text, { width: 220, margin: 1, errorCorrectionLevel: 'M' })
      .then(setQrUrl)
      .catch(() => setQrUrl(''))
  }, [sign])

  function set(key: keyof SignData) {
    return (e: React.ChangeEvent<HTMLInputElement>) => setSign(s => ({ ...s, [key]: e.target.value }))
  }

  function handlePrint() {
    const win = window.open('', '_blank', 'width=900,height=700')
    if (!win) { window.print(); return }
    win.document.write(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>Site Sign – ${sign.projectNumber}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: Arial, Helvetica, sans-serif; background: #fff; padding: 32px; }
  #sign-root { border: 4px solid #1e293b; border-radius: 12px; padding: 32px; max-width: 760px; margin: auto; }
  .header { text-align: center; border-bottom: 3px solid #1e293b; padding-bottom: 16px; margin-bottom: 24px; }
  .badge { font-size: 11px; font-weight: bold; letter-spacing: 2px; text-transform: uppercase; color: #64748b; margin-bottom: 4px; }
  .project-name { font-size: 24px; font-weight: 900; color: #0f172a; line-height: 1.2; }
  .project-num  { font-size: 16px; font-weight: 700; color: #1d4ed8; margin-top: 4px; }
  .body { display: grid; grid-template-columns: 1fr auto; gap: 24px; }
  .fields { display: flex; flex-direction: column; gap: 16px; }
  .field-label { font-size: 10px; font-weight: 700; letter-spacing: 1.5px; text-transform: uppercase; color: #94a3b8; }
  .field-value { font-size: 14px; font-weight: 600; color: #1e293b; margin-top: 2px; }
  .qr-col { display: flex; flex-direction: column; align-items: center; justify-content: center; }
  .qr-img { width: 160px; height: 160px; }
  .qr-caption { font-size: 10px; color: #94a3b8; margin-top: 6px; text-align: center; }
  .footer { margin-top: 24px; padding-top: 12px; border-top: 1px solid #e2e8f0; display: flex; justify-content: space-between; font-size: 11px; color: #94a3b8; }
</style>
</head>
<body>
<div id="sign-root">
  <div class="header">
    <div class="badge">Infrastructure Project</div>
    <div class="project-name">${sign.projectName || 'Project Name'}</div>
    <div class="project-num">${sign.projectNumber}</div>
  </div>
  <div class="body">
    <div class="fields">
      ${[
        ['📍 Site Address', sign.siteAddress],
        ['👷 Engineer', sign.engineer],
        ['🏗️ Contractor', sign.contractor],
        ['📅 Start Date', sign.startDate],
        ['🚨 Emergency', sign.emergencyContact],
      ].map(([label, value]) => `
        <div>
          <div class="field-label">${label}</div>
          <div class="field-value">${value || '—'}</div>
        </div>`).join('')}
    </div>
    <div class="qr-col">
      ${qrUrl ? `<img src="${qrUrl}" alt="QR" class="qr-img"/>` : ''}
      <div class="qr-caption">Scan for project details</div>
    </div>
  </div>
  <div class="footer">
    <span>Generated by TPT Infrastructure Engineer</span>
    <span>${new Date().toLocaleDateString('en-NZ')}</span>
  </div>
</div>
<script>window.onload = () => { window.print(); window.close(); }<\/script>
</body>
</html>`)
    win.document.close()
  }

  const fields: [keyof SignData, string][] = [
    ['projectName',      'Project Name'],
    ['projectNumber',    'Project Number'],
    ['siteAddress',      'Site Address'],
    ['engineer',         'Engineer (CPEng)'],
    ['contractor',       'Principal Contractor'],
    ['startDate',        'Start Date'],
    ['emergencyContact', 'Emergency Contact'],
    ['url',              'QR Code URL'],
  ]

  return (
    <div className="p-6 bg-gray-50 min-h-screen">
      <div className="max-w-5xl mx-auto">
        <div className="flex justify-between items-start mb-6">
          <div>
            <h2 className="text-2xl font-bold text-gray-800">QR Site Sign</h2>
            <p className="text-sm text-gray-500 mt-0.5">Printable project board with embedded QR code</p>
          </div>
          <button onClick={handlePrint}
            className="bg-blue-600 hover:bg-blue-700 text-white px-5 py-2 rounded-lg font-medium flex items-center gap-2"
          >
            🖨️ Print / Save PDF
          </button>
        </div>

        <div className="grid grid-cols-2 gap-6">
          {/* Form */}
          <div className="bg-white rounded-lg shadow p-5 space-y-3">
            <h3 className="font-semibold text-gray-700">Sign Details</h3>
            {fields.map(([key, label]) => (
              <div key={key}>
                <label className="text-xs text-gray-500 block mb-0.5">{label}</label>
                <input value={sign[key]} onChange={set(key)}
                  className="w-full border border-gray-300 rounded px-3 py-1.5 text-sm" />
              </div>
            ))}
          </div>

          {/* Preview */}
          <div>
            <div ref={signRef}
              className="bg-white border-4 border-gray-800 rounded-xl p-8 shadow-lg"
              style={{ fontFamily: 'Arial, Helvetica, sans-serif' }}
            >
              {/* Header */}
              <div className="text-center border-b-2 border-gray-800 pb-4 mb-6">
                <div className="text-xs font-bold tracking-widest text-gray-400 uppercase mb-1">
                  Infrastructure Project
                </div>
                <h1 className="text-2xl font-black text-gray-900 leading-tight">
                  {sign.projectName || 'Project Name'}
                </h1>
                <div className="text-base font-bold text-blue-700 mt-1">{sign.projectNumber}</div>
              </div>

              {/* Body */}
              <div className="grid grid-cols-2 gap-5 mb-6">
                <div className="space-y-4">
                  {[
                    ['📍 Site Address', sign.siteAddress],
                    ['👷 Engineer',     sign.engineer],
                    ['🏗️ Contractor',   sign.contractor],
                    ['📅 Start Date',   sign.startDate],
                    ['🚨 Emergency',    sign.emergencyContact],
                  ].map(([label, value]) => (
                    <div key={label}>
                      <div className="text-xs font-bold text-gray-400 uppercase tracking-wide">{label}</div>
                      <div className="font-semibold text-gray-800 text-sm mt-0.5">{value || '—'}</div>
                    </div>
                  ))}
                </div>
                <div className="flex flex-col items-center justify-center">
                  {qrUrl && (
                    <>
                      <img src={qrUrl} alt="QR Code" className="w-36 h-36" />
                      <div className="text-xs text-gray-400 mt-2 text-center">
                        Scan for project details
                      </div>
                    </>
                  )}
                </div>
              </div>

              {/* Footer */}
              <div className="border-t border-gray-200 pt-3 flex justify-between text-xs text-gray-400">
                <span>TPT Infrastructure Engineer</span>
                <span>{new Date().toLocaleDateString('en-NZ')}</span>
              </div>
            </div>
            <p className="text-xs text-gray-400 text-center mt-3">
              Live preview · "Print / Save PDF" opens a formatted print dialog
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}

export default QRSiteSign
